### ISSUE TITLE
Access individual frames without the DOM

### ISSUE THREAD

**Issue by jcubic** [tholman/ascii-morph#2]
Is using DOM the only option? It would be nice if you can use the library without the DOM. and do whatever you want with the frames.

```javascript
AsciiMorph.render(bird, function(string) {
   // I can render this on canvas
   // the callback will be called on each frame
});
AsciiMorph.morph(mona);
```

or Maybe just return list of frames.

```javascript
AsciiMorph.toFrames(bird, mona);
```

with this you can use Canvas to render the animation or use he terminal.

**Comment by MarketingPip** [comment]
@jcubic - did you ever port this / make a fork? (I have been stupidly using observers to do things like this) but frames method is ideal (true CLI) which I should have been doing from the start .-.

**Comment by jcubic** [comment]
No, I totally forgot about this project and I didn't even look at the code. Maybe I should revisit.

**Comment by jcubic** [comment]
I created a copy of the repo (not a fork):

https://github.com/jcubic/ascii-morph

Will refactor the code and make it DOM independent, so you can use CLI or ReactJS.

**Comment by jcubic** [comment]
I've finished refactoring and published to NPM.

**Comment by MarketingPip** [comment]
@jcubic - wow hahaha! That was quick. I'll try throwing up that gist / code I have for you as a gift in return for doing this!

**Comment by tholman** [comment]
I love open source

**Comment by MarketingPip** [comment]
@tholman - my exact thought. 


That said - thank YOU for sharing this cool library. That said (maybe JCubic will make a nice PR - now we see you are active hahahahaa) cheers 🍻

**Comment by MarketingPip** [comment]
@jcubic - just playing around here too with your changes. I think a frame approach would be ideal / step using a yield etc... 

(as well if not - a mutation observer is needed) - currently no way to catch issues with this.

**Comment by MarketingPip** [comment]
@jcubic @tholman - taking a gander / lucky shot and seeing if we can all possibility make a solution for this. Kind of asciimorph related (for a library / project) - I am trying to build. Can not seem to figure out how to properly keep text in tack.

Hoping to implement a effect like so - ie: moves from one scene to another in a circular motion, like the hands of a clock. 

![image](https://github.com/user-attachments/assets/0728490b-f426-489c-91d6-d026622fabb6)


See CodePen [here](https://codepen.io/MarketingPipeline/pen/RwXGdxP?editors=1111)


Ideally would be nice to implement a design pattern like jcubic suggest earlier in this code - rather than his current fork. As it seems like a better usage for developers. (Hoping ideally to steal ASCII morph as import too - combing a library of cool transitions.) - Have a few others finished currently.
